services:
  turtlesim:
    build:
      context: .
    image: turtlesim-catch-them-all:dev
    container_name: turtlesim-catch-them-all
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    stdin_open: true
    tty: true

  controller:
    image: turtlesim-catch-them-all:dev
    depends_on:
      - turtlesim
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
    network_mode: host
    stdin_open: true
    tty: true
    command: ros2 run turtlesim_catch_them_all Turtle_ctrl_node
    profiles:
      - tools
